version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "androidx.core:core-ktx"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "androidx.recyclerview:recyclerview"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "androidx.appcompat:appcompat"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
