version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      android-root:
        patterns: ["*"]
  - package-ecosystem: "gradle"
    directory: "/ticker/android"
    schedule:
      interval: "weekly"
    groups:
      core-line-android:
        patterns: ["*"]
  - package-ecosystem: "gradle"
    directory: "/shift"
    schedule:
      interval: "weekly"
    groups:
      core-shift:
        patterns: ["*"]
  - package-ecosystem: "gradle"
    directory: "/doctor"
    schedule:
      interval: "weekly"
    groups:
      core-doctor:
        patterns: ["*"]
  - package-ecosystem: "gradle"
    directory: "/motion-plugin"
    schedule:
      interval: "weekly"
    groups:
      core-motion:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/ticker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
