#!/usr/bin/env python3
"""Catch full-screen layouts that overflow a TV viewport without scrolling.

Why this exists
---------------
activity_settings.xml shipped in 1.8.20 with no scroll container, on the
reasoning that "four rows and a footer fit inside the safe area at 1080p".
They did not. The height was reasoned off a 1920x1080 *pixel* mockup; Android
lays out in dp, and a 1080p Android TV reports 960x540dp. The content came to
roughly 615dp against 540dp available, and because the root was a plain
vertical LinearLayout holding a weight=1 spacer, the overflow was clipped in
silence: no scrollbar, no focus escape, just a Clear button and a footer the
tester could not reach.

Nothing in the repo caught it. check_ui_resources.py resolves R.* references
and test_resource_parity.py compares resource sets across modules; neither one
asks whether the pixels fit. This does.

What it checks
--------------
For every layout whose root is a vertical LinearLayout at match_parent, sum the
height its children need in the vertical flow. One child may be the screen's
vertical scroll boundary: a scroll container that fills the leftover space
(0dp + weight, or match_parent). That child costs nothing, because it scrolls.
Every other child is fixed and must fit, so the sum of the fixed siblings plus
the root's own padding has to stay inside the viewport.

That framing is deliberate. Checking only "does a scroller appear anywhere in
the tree" would exempt a screen because of a horizontal chip row nested in its
header, and would let the settings ScrollView be deleted without the pin
noticing so long as some other RecyclerView survived. A horizontal RecyclerView
sitting in the vertical flow is measured like any other fixed child.

Known limits, stated rather than hidden:

* Text height is modelled as textSize * LINE_FACTOR, close for Roboto but not
  exact, and nothing here knows what a SwitchCompat measures. So the gate is
  slack by TOLERANCE_DP and catches a layout over by a whole row, which is the
  mistake that actually happened, not the last few dp.
* android:visibility="gone" children are skipped, matching how Android measures
  them. A view that is gone in XML and shown at runtime is therefore invisible
  to this check. activity_main.xml relies on that: empty_state and grid are
  both weighted and mutually exclusive, and only the XML says which is live.

A layout that legitimately needs more room passes by giving its overflowing
content a scroll boundary. That is the fix, not an exemption.

Wiring: this file has test_* functions but no TestCase, so `unittest discover`
skips it the same way it skips test_resource_parity.py and the Core Shift
scripts. CI runs the Python suites by naming each file, so this one is listed
explicitly in build.yml and suite-ci.yml. Add it there, or it is not a gate.
"""
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ANDROID = "{http://schemas.android.com/apk/res/android}"

# Android TV at 1080p reports 960x540dp (xhdpi). 720p sets report the same dp
# box at tvdpi, so one number covers both.
VIEWPORT_DP = 540.0

# Slack for the modelling error described above: roughly one settings row.
TOLERANCE_DP = 60.0

# Roboto's ascent+descent lands near 1.17x the type size; 1.2 is the usual
# working figure and errs toward predicting *more* height, which is the safe
# direction for a gate that fails on overflow.
LINE_FACTOR = 1.2

# Containers that can absorb vertical overflow by scrolling.
SCROLLERS = ("ScrollView", "NestedScrollView", "RecyclerView", "ViewPager", "ViewPager2")

# Only these genuinely scroll a stack of content vertically; a RecyclerView may
# be a horizontal chip row, so it is not enough to pin the settings screen.
VERTICAL_SCROLLERS = ("ScrollView", "NestedScrollView")

# Every module that ships a layout tree, each with its own dimens. Pop's copies
# are generated by tools/build_pop.py and Pixel Neon's are synced by hand, but
# each one builds a separate APK, so each is measured rather than assumed to
# match app/.
MODULES = {
    "app": ROOT / "app/src/main/res",
    "pop": ROOT / "pop/src/main/res",
    "pixel-neon": ROOT / "pixel-neon/app/src/main/res",
}


def load_dimens(res: Path) -> dict[str, float]:
    out: dict[str, float] = {}
    path = res / "values/dimens.xml"
    if not path.exists():
        return out
    for node in ET.parse(path).getroot().iter("dimen"):
        name, text = node.get("name"), (node.text or "").strip()
        m = re.fullmatch(r"(-?[\d.]+)(dp|sp|dip|px)", text)
        if name and m:
            out[name] = float(m.group(1))
    return out


def dp(value: str | None, dimens: dict[str, float], default: float = 0.0) -> float:
    """Resolve a dimension attribute to dp. Unknown forms fall back to default."""
    if not value:
        return default
    if value.startswith("@dimen/"):
        return dimens.get(value[len("@dimen/"):], default)
    m = re.fullmatch(r"(-?[\d.]+)(dp|sp|dip|px)", value.strip())
    return float(m.group(1)) if m else default


def tag_of(node: ET.Element) -> str:
    return node.tag.rsplit(".", 1)[-1]


def is_gone(node: ET.Element) -> bool:
    return node.get(ANDROID + "visibility") == "gone"


def fills_leftover(node: ET.Element) -> bool:
    """True when this child takes whatever vertical space its siblings leave."""
    h = node.get(ANDROID + "layout_height")
    return h == "match_parent" or (h == "0dp" and bool(node.get(ANDROID + "layout_weight")))


def scroll_boundary(root: ET.Element) -> ET.Element | None:
    """The one direct child that absorbs vertical overflow, if there is one."""
    for child in root:
        if is_gone(child):
            continue
        if tag_of(child) in SCROLLERS and fills_leftover(child):
            return child
    return None


def min_height(node: ET.Element, dimens: dict[str, float]) -> float:
    """Minimum dp this subtree needs.

    A weighted child is flexible only when it is an empty spacer. A weighted
    container that holds content still needs room for that content, so it is
    measured like any other; returning zero for it would hide fixed descendants
    that overflow the space the weight actually wins.
    """
    tag = tag_of(node)
    kids = [k for k in node if not is_gone(k)]

    if not kids and fills_leftover(node) and node.get(ANDROID + "layout_weight"):
        return 0.0

    pad = dp(node.get(ANDROID + "padding"), dimens)
    top = dp(node.get(ANDROID + "paddingTop"), dimens, pad)
    bottom = dp(node.get(ANDROID + "paddingBottom"), dimens, pad)
    own = dp(node.get(ANDROID + "minHeight"), dimens)

    if not kids:
        # Leaf. Text views are the only leaves with intrinsic height here.
        text = dp(node.get(ANDROID + "textSize"), dimens) * LINE_FACTOR
        # SwitchCompat and friends: assume the 48dp TV touch/focus minimum.
        if not text and tag not in ("View", "Space"):
            text = 30.0 if "Switch" in tag else 0.0
        return max(top + bottom + text, own)

    stacks = tag.endswith("LinearLayout") and node.get(ANDROID + "orientation") == "vertical"
    inner = 0.0
    for kid in kids:
        h = (min_height(kid, dimens)
             + dp(kid.get(ANDROID + "layout_marginTop"), dimens)
             + dp(kid.get(ANDROID + "layout_marginBottom"), dimens))
        inner = inner + h if stacks else max(inner, h)
    return max(top + bottom + inner, own)


def fixed_demand(root: ET.Element, dimens: dict[str, float]) -> float:
    """Height the root needs for everything that cannot scroll away."""
    pad = dp(root.get(ANDROID + "padding"), dimens)
    total = (dp(root.get(ANDROID + "paddingTop"), dimens, pad)
             + dp(root.get(ANDROID + "paddingBottom"), dimens, pad))
    boundary = scroll_boundary(root)
    for child in root:
        if is_gone(child) or child is boundary:
            continue
        total += (min_height(child, dimens)
                  + dp(child.get(ANDROID + "layout_marginTop"), dimens)
                  + dp(child.get(ANDROID + "layout_marginBottom"), dimens))
    return total


def full_screen_layouts(res: Path) -> list[Path]:
    out = []
    for p in sorted((res / "layout").glob("activity_*.xml")):
        root = ET.parse(p).getroot()
        if (tag_of(root).endswith("LinearLayout")
                and root.get(ANDROID + "orientation") == "vertical"
                and root.get(ANDROID + "layout_height") == "match_parent"):
            out.append(p)
    return out


def survey() -> list[tuple[str, Path, float, str]]:
    rows = []
    for module, res in MODULES.items():
        if not (res / "layout").is_dir():
            continue
        dimens = load_dimens(res)
        for path in full_screen_layouts(res):
            root = ET.parse(path).getroot()
            boundary = scroll_boundary(root)
            label = (boundary.get(ANDROID + "id") or tag_of(boundary)) if boundary is not None else "none"
            rows.append((module, path, fixed_demand(root, dimens), label.replace("@+id/", "")))
    return rows


def test_full_screen_layouts_fit_or_scroll():
    over = [
        f"{module}/{path.name}: fixed content needs ~{needed:.0f}dp of "
        f"{VIEWPORT_DP:.0f}dp, scroll boundary: {label}"
        for module, path, needed, label in survey()
        if needed > VIEWPORT_DP + TOLERANCE_DP
    ]
    assert not over, "TV layouts overflow without scrolling:\n  " + "\n  ".join(over)


def load_dimens_in(res: Path, subdir: str) -> dict[str, float]:
    out: dict[str, float] = {}
    path = res / subdir / "dimens.xml"
    if not path.is_file():
        return out
    for node in ET.parse(path).getroot().iter("dimen"):
        name, text = node.get("name"), (node.text or "").strip()
        m = re.fullmatch(r"(-?[\d.]+)(dp|sp|dip|px)", text)
        if name and m:
            out[name] = float(m.group(1))
    return out


# The two-pane screens' grid budget, on the design box every panel is
# normalised to (tv.corebuilds.iconpack.TvActivity).
TWO_PANE = {
    "activity_main.xml": ["cb_tile_icon", "cb_card_padding", "cb_card_padding"],
    "activity_wallpapers.xml": ["cb_wp_thumb", "cb_card_padding", "cb_card_padding",
                                "cb_space_sm", "cb_text_label"],
}


def pane_of(root: ET.Element) -> ET.Element | None:
    """The weighted child of the root's weighted horizontal body, if the screen
    is two-pane: home and wallpapers put their grid in it."""
    for child in root:
        if is_gone(child) or not fills_leftover(child):
            continue
        if tag_of(child).endswith("LinearLayout") \
                and child.get(ANDROID + "orientation") == "horizontal":
            for pane in child:
                # The pane is the 0dp+weight child; the rail is match_parent
                # wide, which fills_leftover() also matches.
                if (not is_gone(pane) and pane.get(ANDROID + "layout_weight")
                        and pane.get(ANDROID + "layout_width") == "0dp"):
                    return pane
    return None


def test_two_pane_screens_leave_the_grid_a_full_row():
    """The right pane's chrome plus one tile pitch fits the panel. The grid is
    the pane's weighted remainder; if the pane's fixed children (search, chips)
    plus a single tile exceeded the viewport, the catalogue would show chrome
    and a cropped sliver - the defect the single-pane home screen had before
    the two-pane rebuild. One box is enough now: TvActivity normalises every
    panel to this one before a layout inflates."""
    for module in ("app", "pop"):
        res = MODULES[module]
        dimens = load_dimens(res)
        for name, pitch_parts in TWO_PANE.items():
            root = ET.parse(res / "layout" / name).getroot()
            pane = pane_of(root)
            assert pane is not None, f"{module}/{name}: not two-pane anymore"
            fixed = (dp(root.get(ANDROID + "paddingTop"), dimens,
                         dp(root.get(ANDROID + "padding"), dimens))
                     + dp(root.get(ANDROID + "paddingBottom"), dimens,
                          dp(root.get(ANDROID + "padding"), dimens)))
            for child in pane:
                if is_gone(child) or fills_leftover(child):
                    continue
                fixed += (min_height(child, dimens)
                          + dp(child.get(ANDROID + "layout_marginTop"), dimens)
                          + dp(child.get(ANDROID + "layout_marginBottom"), dimens))
            pitch = sum(dimens.get(part, 0.0) for part in pitch_parts)
            left = VIEWPORT_DP - fixed - pitch
            assert left >= -TOLERANCE_DP, (
                f"{module}/{name}: pane chrome {fixed:.0f}dp + one {pitch:.0f}dp "
                f"tile leaves {left:.0f}dp of {VIEWPORT_DP:.0f}dp - the grid "
                f"loses its first row")


def test_settings_keeps_its_scroll_container():
    """Regression pin for the 1.8.20 clipping bug, independent of the estimate.

    Asserts the boundary is a real vertical scroller in every module that ships
    the screen: a surviving horizontal RecyclerView must not be able to stand in
    for the ScrollView this bug was fixed with.
    """
    checked = 0
    for module, res in MODULES.items():
        path = res / "layout/activity_settings.xml"
        if not path.exists():
            continue
        checked += 1
        boundary = scroll_boundary(ET.parse(path).getroot())
        assert boundary is not None and tag_of(boundary) in VERTICAL_SCROLLERS, (
            f"{module}/activity_settings.xml has no vertical scroll container; "
            f"its rows clip off a 540dp TV viewport without one"
        )
    assert checked == len(MODULES), f"only {checked} of {len(MODULES)} modules carried the screen"


if __name__ == "__main__":
    for module, path, needed, label in survey():
        print(f"{module + '/' + path.name:46s} {needed:6.0f}dp fixed   scrolls: {label}")
    test_full_screen_layouts_fit_or_scroll()
    test_settings_keeps_its_scroll_container()
    print("ok")
