plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "tv.corebuilds.iconpack"
    compileSdk = 34

    defaultConfig {
        applicationId = "tv.corebuilds.iconpack"
        minSdk = 21
        targetSdk = 34
        versionCode = 49
        versionName = "2.3.1"

        // Read by the updater code: where to check for a newer release and
        // which FileProvider authority serves the downloaded APK.
        buildConfigField(
            "String",
            "UPDATE_AUTHORITY",
            "\"tv.corebuilds.iconpack.update\"",
        )
        buildConfigField(
            "String",
            "UPDATE_MANIFEST_URL",
            "\"https://raw.githubusercontent.com/brevityA/CoreBuildsApps/" +
                "main/Latestrelease/version.json\"",
        )
        manifestPlaceholders["fileProviderAuthority"] = "tv.corebuilds.iconpack.update"
        // English-only: resConfigs strips the ~70 translated locales the
        // support libraries ship, which nothing in this app reads.
        resConfigs("en")
        // The square twin (glyphs/) the Banners/Glyphs toggle points
        // launchers at. Empty in the candidate build, which has no companion.
        buildConfigField(
            "String",
            "GLYPHS_PACKAGE",
            "\"tv.corebuilds.iconpack.glyphs\"",
        )
    }

    // Two installable apps out of one module: the same 35 Kotlin files, the
    // same catalog and the same wallpapers, differing only in the art their
    // appfilter maps. A product flavor is the only mechanism that can do this
    // without a second copy of res/ — two source sets both providing
    // res/xml/appfilter.xml is a duplicate-resource merge error, which is
    // exactly what the retired Pixel Neon forked its Kotlin to get around and
    // then drifted on (see the comment in tools/check_ui_resources.py).
    //
    // src/glyphs/ carries the square appfilter and browser, generated by
    // tools/build_icons.py into the same tree it writes Core Builds Glyphs'
    // from, and tests/test_glyphs_pack.py holds those two trees identical.
    flavorDimensions += "art"
    productFlavors {
        create("banners") {
            dimension = "art"
            // Deliberately empty: the icon pack is what defaultConfig already
            // describes — its package id, its label, its updater feed, and a
            // companion to offer when the art style is switched to Glyphs.
        }
        create("glyphs") {
            dimension = "art"
            applicationId = "tv.corebuilds.glyphs"
            resValue("string", "app_name", "Core Builds Glyphs")
            // Not tv.corebuilds.iconpack.glyphs: that is the resource-only
            // companion the Art style toggle installs, and two apps cannot
            // hold one package name. Both ship; a launcher's icon-pack list
            // shows both, and they are told apart by label.
            //
            // The provider authority has to move with the package id. Two
            // installed apps declaring one FileProvider authority is
            // INSTALL_FAILED_CONFLICTING_PROVIDER, and the icon pack and this
            // app are meant to be installed side by side.
            manifestPlaceholders["fileProviderAuthority"] = "tv.corebuilds.glyphs.update"
            buildConfigField("String", "UPDATE_AUTHORITY", "\"tv.corebuilds.glyphs.update\"")
            // No feed of its own yet — Latestrelease/ carries the icon pack's
            // — and polling that one would offer this app the banner APK,
            // which it cannot install over itself. UpdateChecker names the
            // gap instead of failing on a blank URL.
            buildConfigField("String", "UPDATE_MANIFEST_URL", "\"\"")
            // This variant *is* a glyph pack: there is no companion for it to
            // fetch and no second style to switch to, so the Art style toggle
            // stays hidden exactly as it does in the candidate build, which
            // has always shipped an empty package here.
            buildConfigField("String", "GLYPHS_PACKAGE", "\"\"")
        }
    }

    // This variant is intentionally separate from both production release and
    // the ordinary debug build. It is for maintainer-controlled Android TV
    // testing only: the suffix makes it install beside the production pack,
    // while initWith(debug) guarantees the production signing configuration is
    // never consulted.
    buildTypes {
        create("candidate") {
            initWith(getByName("debug"))
            applicationIdSuffix = ".test"
            val sourceCommit = providers.gradleProperty("testSourceCommit").orElse("local").get()
            versionNameSuffix = "-test.$sourceCommit"
            resValue("string", "app_name", "Core Builds Icon Pack – Test")
            buildConfigField("String", "TEST_SOURCE_COMMIT", "\"$sourceCommit\"")
            buildConfigField("String", "UPDATE_AUTHORITY", "\"tv.corebuilds.iconpack.test.update\"")
            // Debug-signed: it could never pass the companion's signature
            // check against a release-signed Glyphs APK, so it offers none.
            buildConfigField("String", "GLYPHS_PACKAGE", "\"\"")
            manifestPlaceholders["fileProviderAuthority"] = "tv.corebuilds.iconpack.test.update"
        }
    }

    // Keep the production release signing block below separate from the test
    // build type. In particular, no KEYSTORE_* value is read by :test.

    signingConfigs {
        create("release") {
            // Supplied by CI (see .github/workflows/build.yml) or a local
            // keystore.properties. Unsigned builds still produce a usable
            // debug APK via assembleDebug.
            val ksPath = System.getenv("KEYSTORE_PATH")
            if (ksPath != null && file(ksPath).exists()) {
                storeFile = file(ksPath)
                storePassword = System.getenv("KEYSTORE_PASSWORD")
                keyAlias = System.getenv("KEY_ALIAS")
                keyPassword = System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            // The drawables are only ever resolved by name at runtime
            // (appfilter strings, getIdentifier), which is exactly what the
            // generated res/raw/keep.xml pins — shrinking is safe because
            // the keep set comes from the same catalog as the art.
            isMinifyEnabled = true
            isShrinkResources = true
            val ks = System.getenv("KEYSTORE_PATH")
            if (ks != null && file(ks).exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        buildConfig = true
    }

    androidResources {
        // Already-compressed formats; don't re-crunch.
        noCompress += listOf("png", "webp")
    }
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
}
