"""Renderers: spec -> layout XML, Kotlin, strings, manifest snippet.

The D-pad wiring is computed up front (compute_links) and baked into the
layout as explicit nextFocus* attributes, so generated screens navigate
deterministically on any panel instead of relying on spatial focus search.
"""
from __future__ import annotations

from xml.sax.saxutils import escape as _escape

from .spec import Spec, compute_links, default_initial_focus, focus_levels

DIR_ATTR = {"up": "Up", "down": "Down", "left": "Left", "right": "Right"}

__all__ = ["compute_links", "default_initial_focus", "focus_levels"]


def esc(text: str) -> str:
    return _escape(text, {'"': "&quot;", "'": "&apos;"})


def kt_str(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


class Emitter:
    def __init__(self) -> None:
        self.lines: list[str] = []
        self.depth = 0

    def line(self, text: str = "") -> None:
        self.lines.append("    " * self.depth + text if text else "")

    def open(self, text: str) -> None:
        self.line(text)
        self.depth += 1

    def close(self, text: str) -> None:
        self.depth -= 1
        self.line(text)

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"


# --------------------------------------------------------------------------
# D-pad wiring is computed in spec.py (focus_levels / compute_links) so the
# validator, the CLI and Studio share one model. This module renders it.
# --------------------------------------------------------------------------

def link_attrs(vid: str, links: dict[str, dict[str, str]]) -> list[str]:
    return [
        f'android:nextFocus{DIR_ATTR[d]}="@id/{t}"'
        for d, t in sorted((links.get(vid) or {}).items())
    ]


# --------------------------------------------------------------------------
# Layout XML
# --------------------------------------------------------------------------

BUTTON_DRAWABLE = {"cta": "bg_cta", "ghost": "bg_ghost", "chip": "bg_chip_toggle",
                   "toggle": "bg_chip_toggle"}
BUTTON_INK = {"cta": "cb_cta_ink", "ghost": "cb_ink", "chip": "cb_ink",
              "toggle": "cb_ink"}
BUTTON_SIZE = {"cta": "cb_text_body", "ghost": "cb_text_body",
               "chip": "cb_text_label", "toggle": "cb_text_data"}


def _button_xml(e: Emitter, btn: dict, links: dict, tag: str = "TextView") -> None:
    style = btn.get("style", "ghost")
    e.open(f"<{tag}")
    e.line(f'android:id="@+id/{btn["id"]}"')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    if btn.get("_marginStart"):
        e.line('android:layout_marginStart="@dimen/cb_space_sm"')
    e.line('android:minHeight="@dimen/cb_target_min"')
    e.line('android:gravity="center"')
    e.line(f'android:background="@drawable/{BUTTON_DRAWABLE[style]}"')
    e.line('android:clickable="true"')
    e.line('android:focusable="true"')
    e.line('android:focusableInTouchMode="true"')
    for attr in link_attrs(btn["id"], links):
        e.line(attr)
    e.line('android:paddingStart="@dimen/cb_space_md"')
    e.line('android:paddingEnd="@dimen/cb_space_md"')
    e.line('android:paddingTop="@dimen/cb_space_sm"')
    e.line('android:paddingBottom="@dimen/cb_space_sm"')
    e.line(f'android:text="{btn["text"]}"')
    e.line(f'android:textColor="@color/{BUTTON_INK[style]}"')
    e.line(f'android:textSize="@dimen/{btn.get("size", BUTTON_SIZE[style])}"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1


def _recycler_xml(e: Emitter, vid: str, links: dict, horizontal: bool,
                  weight: bool, gone: bool = False,
                  margin_top: str = "cb_space_md") -> None:
    e.open("<androidx.recyclerview.widget.RecyclerView")
    e.line(f'android:id="@+id/{vid}"')
    e.line('android:layout_width="match_parent"')
    if weight:
        e.line('android:layout_height="0dp"')
    else:
        e.line('android:layout_height="wrap_content"')
    e.line(f'android:layout_marginTop="@dimen/{margin_top}"')
    if weight:
        e.line('android:layout_weight="1"')
    e.line('android:clipToPadding="false"')
    if horizontal:
        e.line('android:orientation="horizontal"')
    if gone:
        e.line('android:visibility="gone"')
    for attr in link_attrs(vid, links):
        e.line(attr)
    e.line("/>")
    e.depth -= 1


def render_layout(spec: Spec, links: dict[str, dict[str, str]]) -> str:
    e = Emitter()
    e.line('<?xml version="1.0" encoding="utf-8"?>')
    e.line(f"<!-- Generated by tools/build_ui.py for {spec.activity}.")
    e.line("     D-pad wiring is explicit nextFocus* throughout; the audit is")
    e.line("     `python tools/validate_ui.py <this file>`. Safe to restyle,")
    e.line("     keep the ids (generated Kotlin points at them). -->")
    e.open("<LinearLayout")
    e.line('xmlns:android="http://schemas.android.com/apk/res/android"')
    e.line(f'android:id="@+id/{spec.prefix}_root"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="match_parent"')
    e.line('android:orientation="vertical"')
    e.line('android:background="@color/cb_night"')
    e.line('android:paddingStart="@dimen/cb_gutter_side"')
    e.line('android:paddingEnd="@dimen/cb_gutter_side"')
    e.line('android:paddingTop="@dimen/cb_gutter_top"')
    e.line('android:paddingBottom="@dimen/cb_gutter_bottom">')
    for block in spec.blocks:
        _render_block(e, spec, block, links)
    e.close("</LinearLayout>")
    return e.text()


def _render_block(e: Emitter, spec: Spec, block: dict,
                  links: dict[str, dict[str, str]]) -> None:
    t = block["type"]
    render = {
        "header": _block_header, "actions": _block_actions,
        "targets": _block_targets, "updatebar": _block_updatebar,
        "chips": _block_chips, "search": _block_search,
        "filterrow": _block_filterrow, "grid": _block_grid,
        "hero": _block_hero, "settings": _block_settings,
        "empty": _block_empty, "selectionbar": _block_selectionbar,
        "hint": _block_hint,
    }[t]
    e.line()
    render(e, spec, block, links)


def _block_header(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:gravity="top"')
    e.line('android:orientation="horizontal">')
    e.open('<LinearLayout')
    e.line('android:layout_width="0dp"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_weight="1"')
    e.line('android:orientation="vertical">')
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:background="@drawable/bg_chip"')
    e.line('android:fontFamily="monospace"')
    e.line('android:paddingStart="@dimen/cb_space_sm"')
    e.line('android:paddingEnd="@dimen/cb_space_sm"')
    e.line('android:paddingTop="7dp"')
    e.line('android:paddingBottom="7dp"')
    e.line('android:letterSpacing="0.18"')
    e.line(f'android:text="{block["kicker"]}"')
    e.line('android:textColor="@color/cb_signal_cyan"')
    e.line('android:textSize="@dimen/cb_text_kicker"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_md"')
    e.line('android:letterSpacing="-0.025"')
    e.line(f'android:text="{block["title"]}"')
    e.line('android:textColor="@color/cb_ink"')
    e.line('android:textSize="@dimen/cb_text_display"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1
    if block.get("showCount", True):
        e.open('<TextView')
        e.line(f'android:id="@+id/{block["count_id"]}"')
        e.line('android:layout_width="wrap_content"')
        e.line('android:layout_height="wrap_content"')
        e.line('android:layout_marginTop="@dimen/cb_space_xs"')
        e.line('android:fontFamily="monospace"')
        e.line('android:letterSpacing="0.02"')
        e.line('android:textColor="@color/cb_slate"')
        e.line('android:textSize="@dimen/cb_text_data" />')
        e.depth -= 1
    e.close('</LinearLayout>')
    side = block.get("side") or []
    if side:
        e.open('<LinearLayout')
        e.line('android:layout_width="wrap_content"')
        e.line('android:layout_height="wrap_content"')
        e.line('android:gravity="end"')
        e.line('android:orientation="vertical">')
        for n, btn in enumerate(side):
            if n > 0:
                e.line()
            _button_xml(e, btn, links)
            if btn.get("sub"):
                e.open('<TextView')
                e.line('android:layout_width="wrap_content"')
                e.line('android:layout_height="wrap_content"')
                e.line('android:layout_marginTop="@dimen/cb_space_xs"')
                e.line('android:gravity="end"')
                e.line(f'android:text="{btn["sub"]}"')
                e.line('android:textColor="@color/cb_slate"')
                e.line('android:textSize="@dimen/cb_text_data" />')
                e.depth -= 1
        e.close('</LinearLayout>')
    e.close('</LinearLayout>')


def _block_actions(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_md"')
    e.line('android:gravity="center_vertical"')
    e.line('android:orientation="horizontal">')
    for n, btn in enumerate(block.get("buttons") or []):
        if n > 0:
            e.line()
        _button_xml(e, dict(btn, _marginStart=n > 0), links)
    e.close('</LinearLayout>')


def _block_targets(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    _recycler_xml(e, block["id"], links, horizontal=True, weight=False,
                  gone=not block.get("visible", False), margin_top="cb_space_sm")


def _block_updatebar(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line(f'android:id="@+id/{block["id"]}"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_md"')
    e.line('android:background="@drawable/bg_update"')
    e.line('android:gravity="center_vertical"')
    e.line('android:orientation="horizontal"')
    e.line('android:paddingStart="@dimen/cb_space_md"')
    e.line('android:paddingEnd="@dimen/cb_space_md"')
    e.line('android:paddingTop="@dimen/cb_space_md"')
    e.line('android:paddingBottom="@dimen/cb_space_md"')
    e.line('android:visibility="gone">')
    e.open('<LinearLayout')
    e.line('android:layout_width="0dp"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_weight="1"')
    e.line('android:orientation="vertical">')
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line(f'android:text="{block["label"]}"')
    e.line('android:textColor="@color/cb_ink"')
    e.line('android:textSize="@dimen/cb_text_label"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="3dp"')
    e.line(f'android:text="{block["sub"]}"')
    e.line('android:textColor="@color/cb_slate"')
    e.line('android:textSize="@dimen/cb_text_data" />')
    e.depth -= 1
    e.close('</LinearLayout>')
    _button_xml(e, {"id": block["button_id"], "style": "cta",
                   "text": block["button"], "size": "cb_text_label"}, links)
    e.close('</LinearLayout>')


def _block_chips(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    _recycler_xml(e, block["id"], links, horizontal=True, weight=False,
                  margin_top="cb_space_lg")


def _block_search(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    _search_xml(e, block["id"], links, width="match_parent",
                margin_top="cb_space_lg", hint=block["hint"])


def _search_xml(e: Emitter, vid: str, links: dict, width: str,
                margin_top: str, hint: str,
                margin_start: str | None = None) -> None:
    e.open('<EditText')
    e.line(f'android:id="@+id/{vid}"')
    e.line(f'android:layout_width="{width}"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:minHeight="@dimen/cb_target_min"')
    if margin_top:
        e.line(f'android:layout_marginTop="@dimen/{margin_top}"')
    if margin_start:
        e.line(f'android:layout_marginStart="@dimen/{margin_start}"')
    e.line('android:background="@drawable/bg_search"')
    e.line('android:focusable="true"')
    e.line('android:focusableInTouchMode="true"')
    for attr in link_attrs(vid, links):
        e.line(attr)
    e.line(f'android:hint="{hint}"')
    e.line('android:imeOptions="actionSearch"')
    e.line('android:importantForAutofill="no"')
    e.line('android:inputType="text"')
    e.line('android:paddingStart="@dimen/cb_space_md"')
    e.line('android:paddingEnd="@dimen/cb_space_md"')
    e.line('android:paddingTop="@dimen/cb_space_sm"')
    e.line('android:paddingBottom="@dimen/cb_space_sm"')
    e.line('android:textColor="@color/cb_ink"')
    e.line('android:textColorHint="@color/cb_slate"')
    e.line('android:textSize="@dimen/cb_text_label" />')
    e.depth -= 1


def _block_filterrow(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_lg"')
    e.line('android:gravity="center_vertical"')
    e.line('android:orientation="horizontal">')
    e.open('<androidx.recyclerview.widget.RecyclerView')
    e.line(f'android:id="@+id/{block["chips_id"]}"')
    e.line('android:layout_width="0dp"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_weight="1"')
    e.line('android:clipToPadding="false"')
    e.line('android:orientation="horizontal"')
    for attr in link_attrs(block["chips_id"], links):
        e.line(attr)
    e.line("/>")
    e.depth -= 1
    _search_xml(e, block["search_id"], links, width="400dp", margin_top="",
                margin_start="cb_space_md", hint=block["hint"])
    e.close('</LinearLayout>')


def _block_grid(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    _recycler_xml(e, block["id"], links, horizontal=False, weight=True)


def _block_hero(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_lg"')
    e.line('android:gravity="center_vertical"')
    e.line('android:orientation="horizontal">')
    e.open('<ImageView')
    e.line('android:layout_width="160dp"')
    e.line('android:layout_height="90dp"')
    e.line(f'android:src="{block.get("art", "@drawable/cb_banner")}"')
    e.line('android:scaleType="centerCrop"')
    e.line('android:contentDescription="@null"')
    e.line('android:importantForAccessibility="no" />')
    e.depth -= 1
    e.open('<LinearLayout')
    e.line('android:layout_width="0dp"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_weight="1"')
    e.line('android:layout_marginStart="@dimen/cb_space_lg"')
    e.line('android:orientation="vertical">')
    if block.get("kicker"):
        e.open('<TextView')
        e.line('android:layout_width="wrap_content"')
        e.line('android:layout_height="wrap_content"')
        e.line('android:fontFamily="monospace"')
        e.line('android:letterSpacing="0.18"')
        e.line(f'android:text="{block["kicker"]}"')
        e.line('android:textColor="@color/cb_signal_cyan"')
        e.line('android:textSize="@dimen/cb_text_kicker"')
        e.line('android:textStyle="bold" />')
        e.depth -= 1
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_xs"')
    e.line(f'android:text="{block["title"]}"')
    e.line('android:textColor="@color/cb_ink"')
    e.line('android:textSize="@dimen/cb_text_section"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1
    if block.get("meta"):
        e.open('<TextView')
        e.line('android:layout_width="wrap_content"')
        e.line('android:layout_height="wrap_content"')
        e.line('android:layout_marginTop="@dimen/cb_space_xs"')
        e.line(f'android:text="{block["meta"]}"')
        e.line('android:textColor="@color/cb_slate"')
        e.line('android:textSize="@dimen/cb_text_label" />')
        e.depth -= 1
    e.close('</LinearLayout>')
    e.close('</LinearLayout>')


def _block_settings(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_md"')
    e.line('android:orientation="vertical">')
    for n, row in enumerate(block.get("rows") or []):
        if n > 0:
            e.line()
        e.open('<LinearLayout')
        e.line(f'android:id="@+id/{row["id"]}"')
        e.line('android:layout_width="match_parent"')
        e.line('android:layout_height="wrap_content"')
        e.line('android:minHeight="@dimen/cb_target_min"')
        e.line('android:gravity="center_vertical"')
        e.line('android:background="@drawable/bg_ghost"')
        e.line('android:clickable="true"')
        e.line('android:focusable="true"')
        e.line('android:focusableInTouchMode="true"')
        for attr in link_attrs(row["id"], links):
            e.line(attr)
        e.line('android:paddingStart="@dimen/cb_space_md"')
        e.line('android:paddingEnd="@dimen/cb_space_md"')
        e.line('android:paddingTop="@dimen/cb_space_sm"')
        e.line('android:paddingBottom="@dimen/cb_space_sm"')
        e.line('android:orientation="horizontal">')
        e.open('<TextView')
        e.line('android:layout_width="0dp"')
        e.line('android:layout_height="wrap_content"')
        e.line('android:layout_weight="1"')
        e.line(f'android:text="{row["label"]}"')
        e.line('android:textColor="@color/cb_ink"')
        e.line('android:textSize="@dimen/cb_text_label"')
        e.line('android:textStyle="bold" />')
        e.depth -= 1
        if row.get("value"):
            e.open('<TextView')
            e.line('android:layout_width="wrap_content"')
            e.line('android:layout_height="wrap_content"')
            e.line(f'android:text="{row["value"]}"')
            e.line('android:textColor="@color/cb_slate"')
            e.line('android:textSize="@dimen/cb_text_label" />')
            e.depth -= 1
        e.close('</LinearLayout>')
    e.close('</LinearLayout>')


def _block_empty(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line(f'android:id="@+id/{block["id"]}"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="0dp"')
    e.line('android:layout_weight="1"')
    e.line('android:layout_marginTop="@dimen/cb_space_xl"')
    e.line('android:gravity="center"')
    e.line('android:orientation="vertical"')
    e.line('android:visibility="gone">')
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line(f'android:text="{block["title"]}"')
    e.line('android:textColor="@color/cb_ink"')
    e.line('android:textSize="@dimen/cb_text_section"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1
    e.open('<TextView')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_xs"')
    e.line('android:gravity="center"')
    e.line('android:maxWidth="620dp"')
    e.line(f'android:text="{block["body"]}"')
    e.line('android:textColor="@color/cb_slate"')
    e.line('android:textSize="@dimen/cb_text_label" />')
    e.depth -= 1
    e.open('<LinearLayout')
    e.line('android:layout_width="wrap_content"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_md"')
    e.line('android:orientation="horizontal">')
    _button_xml(e, {"id": block["primary_id"], "style": "cta",
                   "text": block["primary"], "size": "cb_text_label"}, links)
    e.line()
    _button_xml(e, {"id": block["secondary_id"], "style": "ghost",
                   "text": block["secondary"], "size": "cb_text_label",
                   "_marginStart": True}, links)
    e.close('</LinearLayout>')
    e.close('</LinearLayout>')


def _block_selectionbar(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<LinearLayout')
    e.line(f'android:id="@+id/{block["id"]}"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_sm"')
    e.line('android:gravity="center_vertical"')
    e.line('android:orientation="horizontal"')
    e.line('android:visibility="gone">')
    e.open('<TextView')
    e.line('android:layout_width="0dp"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_weight="1"')
    e.line('android:fontFamily="monospace"')
    e.line(f'android:text="{block["count"]}"')
    e.line('android:textColor="@color/cb_signal_cyan"')
    e.line('android:textSize="@dimen/cb_text_label" />')
    e.depth -= 1
    for n, b in enumerate(block.get("buttons") or []):
        e.line()
        _button_xml(e, dict(b, size="cb_text_data", _marginStart=n > 0), links)
    e.close('</LinearLayout>')


def _block_hint(e: Emitter, spec: Spec, block: dict, links: dict) -> None:
    e.open('<TextView')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_xs"')
    e.line(f'android:text="{block["text"]}"')
    e.line('android:textColor="@color/cb_signal_cyan"')
    e.line('android:textSize="@dimen/cb_text_label" />')
    e.depth -= 1


# --------------------------------------------------------------------------
# Item layout + custom adapter
# --------------------------------------------------------------------------

def render_item_layout(spec: Spec) -> str:
    e = Emitter()
    e.line('<?xml version="1.0" encoding="utf-8"?>')
    e.line(f"<!-- Generated by tools/build_ui.py for {spec.screen}Adapter. -->")
    e.open('<LinearLayout')
    e.line('xmlns:android="http://schemas.android.com/apk/res/android"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:background="@drawable/bg_card"')
    e.line('android:clickable="true"')
    e.line('android:focusable="true"')
    e.line('android:focusableInTouchMode="true"')
    e.line('android:gravity="center_horizontal"')
    e.line('android:minHeight="@dimen/cb_target_min"')
    e.line('android:orientation="vertical"')
    e.line('android:padding="@dimen/cb_card_padding">')
    e.open('<ImageView')
    e.line(f'android:id="@+id/{spec.prefix}_item_image"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="@dimen/cb_card_icon"')
    e.line('android:contentDescription="@null"')
    e.line('android:importantForAccessibility="no"')
    e.line('android:scaleType="fitCenter" />')
    e.depth -= 1
    e.open('<TextView')
    e.line(f'android:id="@+id/{spec.prefix}_item_title"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:layout_marginTop="@dimen/cb_space_sm"')
    e.line('android:ellipsize="end"')
    e.line('android:gravity="center"')
    e.line('android:maxLines="1"')
    e.line('android:textColor="@color/cb_ink"')
    e.line('android:textSize="@dimen/cb_text_label"')
    e.line('android:textStyle="bold" />')
    e.depth -= 1
    e.open('<TextView')
    e.line(f'android:id="@+id/{spec.prefix}_item_sub"')
    e.line('android:layout_width="match_parent"')
    e.line('android:layout_height="wrap_content"')
    e.line('android:ellipsize="end"')
    e.line('android:gravity="center"')
    e.line('android:maxLines="1"')
    e.line('android:textColor="@color/cb_slate"')
    e.line('android:textSize="@dimen/cb_text_data" />')
    e.depth -= 1
    e.close('</LinearLayout>')
    return e.text()


def render_adapter(spec: Spec) -> str:
    """A working starter adapter: stable ids + DiffUtil + focus zoom."""
    p = spec.prefix
    return f"""package {spec.package}

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ImageView
import android.widget.TextView
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.RecyclerView
import {spec.package}.ui.TvFocus

/**
 * Generated by tools/build_ui.py for {spec.activity}.
 *
 * Stable ids + DiffUtil: filtering never drops the D-pad highlight, and item
 * animations survive data changes. Focus zoom is attached here (not in the
 * Activity) so it applies per view-holder.
 *
 * TODO: replace [sampleRows] with your data source.
 */
class {spec.screen}Adapter(
    private var items: List<Row>,
    private val onActivate: (Row) -> Unit
) : RecyclerView.Adapter<{spec.screen}Adapter.VH>() {{

    data class Row(
        val key: String,
        val title: String,
        val sub: String,
        /** Drawable name resolved at bind time; blank leaves the art empty. */
        val drawable: String = ""
    )

    class VH(view: View) : RecyclerView.ViewHolder(view) {{
        val image: ImageView = view.findViewById(R.id.{p}_item_image)
        val title: TextView = view.findViewById(R.id.{p}_item_title)
        val sub: TextView = view.findViewById(R.id.{p}_item_sub)
    }}

    init {{
        setHasStableIds(true)
    }}

    override fun getItemId(position: Int): Long = items[position].key.hashCode().toLong()

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): VH {{
        val v = LayoutInflater.from(parent.context)
            .inflate(R.layout.item_{p}, parent, false)
        TvFocus.attach(v)
        return VH(v)
    }}

    override fun onBindViewHolder(holder: VH, position: Int) {{
        val item = items[position]
        val ctx = holder.image.context
        if (item.drawable.isNotEmpty()) {{
            val id = ctx.resources.getIdentifier(item.drawable, "drawable", ctx.packageName)
            if (id != 0) holder.image.setImageResource(id)
        }}
        holder.title.text = item.title
        holder.sub.text = item.sub
        holder.itemView.contentDescription = item.title
        holder.itemView.setOnClickListener {{ onActivate(item) }}
    }}

    override fun getItemCount() = items.size

    fun submit(next: List<Row>) {{
        val previous = items
        val result = DiffUtil.calculateDiff(object : DiffUtil.Callback() {{
            override fun getOldListSize() = previous.size
            override fun getNewListSize() = next.size
            override fun areItemsTheSame(old: Int, new: Int) =
                previous[old].key == next[new].key
            override fun areContentsTheSame(old: Int, new: Int) =
                previous[old] == next[new]
        }})
        items = next
        result.dispatchUpdatesTo(this)
    }}

    companion object {{
        /** Placeholder rows so the generated screen runs before data lands. */
        fun sampleRows(): List<Row> = listOf(
            Row("row_1", "First row", "subtitle", "cb_banner"),
            Row("row_2", "Second row", "subtitle", "cb_banner"),
            Row("row_3", "Third row", "subtitle", "cb_banner")
        )
    }}
}}
"""


# --------------------------------------------------------------------------
# Activity
# --------------------------------------------------------------------------

def _blocks_of(spec: Spec, *types: str) -> list[dict]:
    return [b for b in spec.blocks if b["type"] in types]


def render_activity(spec: Spec, links: dict[str, dict[str, str]]) -> str:
    grids = _blocks_of(spec, "grid")
    chips_blocks = _blocks_of(spec, "chips", "filterrow")
    searches = _blocks_of(spec, "search", "filterrow")
    has_chips = bool(chips_blocks)
    has_search = bool(searches)
    grid = grids[0] if grids else None
    source = grid["source"] if grid else ""
    filterable = grid is not None and source in ("icons", "walls") and (
        has_chips or has_search)
    header = _blocks_of(spec, "header")[0]
    count_id = header.get("count_id") if header.get("showCount", True) else None

    chips_id = chips_keys = None
    if chips_blocks:
        cb = chips_blocks[0]
        chips_id = cb["chips_id"] if cb["type"] == "filterrow" else cb["id"]
        chips_keys = (cb.get("keys") or ["ALL"], cb.get("labels") or ["All"])
    search_id = None
    if searches:
        sb = searches[0]
        search_id = sb["search_id"] if sb["type"] == "filterrow" else sb["id"]

    initial = spec.dpad.get("initialFocus") or _default_initial(spec)
    anim = spec.anim

    imports = [
        "import android.content.Intent",
        "import android.os.Bundle",
        "import android.view.View",
        "import android.widget.TextView",
        "import android.widget.Toast",
        "import androidx.appcompat.app.AppCompatActivity",
    ]
    if grid:
        imports.append("import androidx.recyclerview.widget.GridLayoutManager")
    if chips_blocks or _blocks_of(spec, "targets"):
        imports.append("import androidx.recyclerview.widget.LinearLayoutManager")
    if grids or chips_blocks or _blocks_of(spec, "targets"):
        imports.append("import androidx.recyclerview.widget.RecyclerView")
    if has_search and filterable:
        imports += ["import android.text.Editable",
                    "import android.text.TextWatcher",
                    "import android.widget.EditText"]
    imports += [f"import {spec.package}.ui.DpadNav",
                f"import {spec.package}.ui.TvFocus",
                f"import {spec.package}.ui.focusFirst"]
    has_go = any("go" in b for b in _all_buttons(spec))
    if not has_go:
        imports = [i for i in imports if i != "import android.content.Intent"]

    e = Emitter()
    e.line(f"package {spec.package}")
    e.line()
    for imp in imports:
        e.line(imp)
    e.line()
    e.line("/**")
    e.line(f" * Generated by tools/build_ui.py for R.layout.{spec.layout}.")
    e.line(" *")
    e.line(" * D-pad: every focusable carries explicit nextFocus* (see the layout),")
    e.line(" * the grid escapes its first row upward via DpadNav.installTopEdge, and")
    e.line(" * contextual bars re-chain their neighbours when they toggle.")
    e.line(" * Motion: TvFocus zoom on buttons and grid items, staggered enter.")
    e.line(" * Audit any restyle with `python tools/validate_ui.py <layout>`.")
    e.line(" */")
    e.line(f"class {spec.activity} : AppCompatActivity() {{")
    e.line()
    # fields
    if source == "icons":
        e.line("    private lateinit var allIcons: List<IconAdapter.IconItem>")
        e.line("    private lateinit var gridAdapter: IconAdapter")
        if has_chips:
            e.line('    private var category = "ALL"')
        if has_search:
            e.line('    private var query = ""')
    elif source == "walls":
        e.line("    private lateinit var allWalls: List<Wallpaper>")
        e.line("    private lateinit var gridAdapter: WallpaperAdapter")
        if has_chips:
            e.line('    private var series = "ALL"')
    elif grid:
        e.line(f"    private lateinit var gridAdapter: {spec.screen}Adapter")
    if has_chips:
        e.line("    private lateinit var chipAdapter: ChipAdapter")
    if has_chips or grid or has_search:
        e.line()
    e.line("    override fun onCreate(savedInstanceState: Bundle?) {")
    e.line("        super.onCreate(savedInstanceState)")
    e.line(f"        setContentView(R.layout.{spec.layout})")
    e.line()
    # Data loads before any block binds: catalog chips read the same lists
    # the grid shows, so chips and grid can never disagree.
    if source == "icons":
        e.line("        val drawables = resources.getStringArray(R.array.icon_pack)")
        e.line("        val names = resources.getStringArray(R.array.icon_names)")
        e.line("        val cats = resources.getStringArray(R.array.icon_categories)")
        e.line("        allIcons = drawables.indices.map { i ->")
        e.line("            IconAdapter.IconItem(drawables[i],")
        e.line("                names.getOrElse(i) { drawables[i] },")
        e.line('                cats.getOrElse(i) { "APP" })')
        e.line("        }")
        e.line()
    elif source == "walls":
        e.line(f"        allWalls = WallpaperCatalog.load(this)")
        e.line()

    for block in spec.blocks:
        _activity_block(e, spec, block, links, {
            "grid": grid, "source": source, "filterable": filterable,
            "chips_id": chips_id, "chips_keys": chips_keys,
            "search_id": search_id, "count_id": count_id,
        })

    e.line(f"        findViewById<View>(R.id.{initial}).focusFirst()")
    if anim.get("enter", True):
        e.line(f"        TvFocus.playEnter(findViewById(R.id.{spec.prefix}_root))")
        if grid:
            e.line(f"        TvFocus.playListEnter(findViewById(R.id.{grid['id']}))")
    e.line("    }")
    e.line()

    if filterable:
        _activity_filter(e, spec, grid, chips_id, search_id, count_id,
                         _blocks_of(spec, "empty"))
    for block in _blocks_of(spec, "updatebar", "selectionbar"):
        _activity_bar_toggle(e, block, links)

    e.line("    private fun toast(msg: String) =")
    e.line("        Toast.makeText(this, msg, Toast.LENGTH_SHORT).show()")
    e.line("}")
    e.line()
    return _apply_anim_overrides(e.text(), spec.anim)


def _all_buttons(spec: Spec) -> list[dict]:
    out: list[dict] = []
    for block in spec.blocks:
        out += list(block.get("side") or []) + list(block.get("buttons") or [])
    return out


def _default_initial(spec: Spec) -> str:
    return default_initial_focus(spec)


def _activity_block(e: Emitter, spec: Spec, block: dict, links: dict, ctx: dict) -> None:
    t = block["type"]
    if t == "header":
        for btn in block.get("side") or []:
            _activity_button(e, btn)
    elif t == "actions":
        for btn in block.get("buttons") or []:
            _activity_button(e, btn)
    elif t == "settings":
        for row in block.get("rows") or []:
            _activity_button(e, {"id": row["id"], "text": row["label"],
                                 **({"go": row["go"]} if "go" in row else {})})
    elif t == "targets":
        vid = block["id"]
        e.line(f"        findViewById<RecyclerView>(R.id.{vid}).apply {{")
        e.line("            layoutManager = LinearLayoutManager(")
        e.line(f"                this@{spec.activity}, LinearLayoutManager.HORIZONTAL, false)")
        e.line("            // TODO: attach a ChipAdapter when targets exist, then")
        e.line("            // DpadNav.chainVertical(...) through this row and show it.")
        e.line("        }")
        e.line()
    elif t == "updatebar":
        bid = block["button_id"]
        e.line(f"        TvFocus.attach(findViewById(R.id.{bid}))")
        e.line(f"        findViewById<TextView>(R.id.{bid}).setOnClickListener {{")
        e.line("            // TODO: update action.")
        e.line(f"            set{IDDENorm(block['id'])}Visible(false)")
        e.line("        }")
        e.line()
    elif t in ("chips", "filterrow"):
        _activity_chips(e, spec, block, ctx)
        if t == "filterrow" and ctx["filterable"]:
            _activity_search(e, spec, block["search_id"], ctx)
    elif t == "search" and ctx["filterable"]:
        _activity_search(e, spec, block["id"], ctx)
    elif t == "search":
        e.line(f"        // Search field: R.id.{block['id']}. TODO: wire a TextWatcher.")
        e.line()
    elif t == "grid":
        _activity_grid(e, spec, block, links, ctx)
    elif t == "empty":
        e.line(f"        TvFocus.attach(findViewById(R.id.{block['primary_id']}))")
        e.line(f"        TvFocus.attach(findViewById(R.id.{block['secondary_id']}))")
        if ctx["filterable"]:
            if ctx["search_id"]:
                e.line(f"        findViewById<TextView>(R.id.{block['primary_id']})"
                       ".setOnClickListener {")
                e.line(f"            findViewById<EditText>(R.id.{ctx['search_id']})"
                       '.setText("")')
                e.line("        }")
            e.line(f"        findViewById<TextView>(R.id.{block['secondary_id']})"
                   ".setOnClickListener {")
            if ctx["chips_id"]:
                e.line('            chipAdapter.select("ALL")')
            e.line("        }")
        else:
            e.line(f"        // Empty-state buttons: R.id.{block['primary_id']},")
            e.line(f"        // R.id.{block['secondary_id']}. TODO: wire undo actions.")
        e.line()
    elif t == "selectionbar":
        for b in block.get("buttons") or []:
            e.line(f"        TvFocus.attach(findViewById(R.id.{b['id']}))")
        e.line("        // TODO: wire selection actions, then set...Visible(false).")
        e.line()
    elif t == "hero":
        e.line("        // TODO: bind hero art/title to the selected item.")
        e.line()


def _activity_button(e: Emitter, btn: dict) -> None:
    bid = btn["id"]
    e.line(f"        TvFocus.attach(findViewById(R.id.{bid}))")
    e.line(f"        findViewById<TextView>(R.id.{bid}).setOnClickListener {{")
    if "go" in btn:
        e.line(f"            startActivity(Intent(this, {btn['go']}::class.java))")
    else:
        label = btn.get("text", "")
        if isinstance(label, str) and label.startswith("@string/"):
            e.line(f"            toast(getString(R.string.{label[8:]}))  // TODO: wire this button.")
        else:
            e.line(f"            toast({bid!r})  // TODO: wire this button.")
    e.line("        }")


def _activity_chips(e: Emitter, spec: Spec, block: dict, ctx: dict) -> None:
    vid = block["chips_id"] if block["type"] == "filterrow" else block["id"]
    if block.get("fromCatalog"):
        e.line('        val chipKeys = mutableListOf("ALL")')
        e.line('        val chipLabels = mutableListOf("All")')
        e.line("        for (s in allWalls.map { it.series }.distinct().sorted()) {")
        e.line("            chipKeys += s")
        e.line("            chipLabels += WallpaperCatalog.seriesLabel(s)")
        e.line("        }")
        e.line("        chipAdapter = ChipAdapter(chipLabels, chipKeys,")
        e.line('            "ALL") { picked ->')
    else:
        keys, labels = ctx["chips_keys"]
        keys_kt = ", ".join(f'"{kt_str(k)}"' for k in keys)
        labels_kt = ", ".join(f'"{kt_str(v)}"' for v in labels)
        e.line(f"        chipAdapter = ChipAdapter(listOf({labels_kt}), listOf({keys_kt}),")
        e.line('            "ALL") { picked ->')
    if ctx["filterable"]:
        field = "category" if ctx["source"] == "icons" else "series"
        e.line(f"            {field} = picked")
        e.line("            applyFilter()")
    else:
        e.line("            toast(picked)  // TODO: filter on picked.")
    e.line("        }")
    e.line(f"        findViewById<RecyclerView>(R.id.{vid}).apply {{")
    e.line("            layoutManager = LinearLayoutManager(")
    e.line(f"                this@{spec.activity}, LinearLayoutManager.HORIZONTAL, false)")
    e.line("            adapter = chipAdapter")
    e.line("        }")
    e.line()


def _activity_search(e: Emitter, spec: Spec, vid: str, ctx: dict) -> None:
    del spec
    e.line(f"        findViewById<EditText>(R.id.{vid})"
           ".addTextChangedListener(object : TextWatcher {")
    e.line("            override fun beforeTextChanged(s: CharSequence?, a: Int, b: Int, c: Int) {}")
    e.line("            override fun onTextChanged(s: CharSequence?, a: Int, b: Int, c: Int) {}")
    e.line("            override fun afterTextChanged(s: Editable?) {")
    e.line("                query = s?.toString().orEmpty()")
    e.line("                applyFilter()")
    e.line("            }")
    e.line("        })")
    e.line()


def _activity_grid(e: Emitter, spec: Spec, block: dict, links: dict, ctx: dict) -> None:
    vid = block["id"]
    source = block["source"]
    cell = block.get("cellDp", 148)
    e.line(f"        findViewById<RecyclerView>(R.id.{vid}).apply {{")
    e.line(f"            layoutManager = GridLayoutManager(this@{spec.activity},")
    e.line(f"                DpadNav.spanForWidth(this@{spec.activity}, {cell}))")
    if source == "icons":
        e.line("            gridAdapter = IconAdapter(allIcons) { item ->")
        e.line("                toast(item.name)  // TODO: pick/apply action.")
        e.line("            }")
    elif source == "walls":
        e.line("            gridAdapter = WallpaperAdapter(allWalls) { wall ->")
        e.line("                toast(wall.title)  // TODO: preview action.")
        e.line("            }")
    else:
        e.line(f"            gridAdapter = {spec.screen}Adapter(")
        e.line(f"                {spec.screen}Adapter.sampleRows()) {{ row ->")
        e.line("                toast(row.title)  // TODO: row action.")
        e.line("            }")
    e.line("            adapter = gridAdapter")
    e.line("            setHasFixedSize(true)")
    e.line("        }")
    if source in ("icons", "walls"):
        # Shared adapters: zoom via attach listener so the adapter stays fork-free.
        e.line(f"        TvFocus.zoomItems(findViewById(R.id.{vid}))")
    up = (links.get(vid) or {}).get("up")
    if up:
        e.line(f"        DpadNav.installTopEdge(findViewById(R.id.{vid}),")
        e.line(f"            {{ (findViewById<RecyclerView>(R.id.{vid}).layoutManager")
        e.line(f"                as GridLayoutManager).spanCount }}, R.id.{up})")
    if ctx.get("count_id") and source in ("icons", "walls"):
        e.line(f"        updateCount(findViewById<TextView>(R.id.{ctx['count_id']}))")
    e.line()


def _activity_filter(e: Emitter, spec: Spec, grid: dict, chips_id: str | None,
                     search_id: str | None, count_id: str | None,
                     empty_blocks: list[dict]) -> None:
    source = grid["source"]
    has_chips = chips_id is not None
    has_search = search_id is not None
    e.line("    private fun applyFilter() {")
    if source == "icons":
        e.line("        val q = query.trim().lowercase()")
        e.line("        val filtered = allIcons.filter { item ->")
        e.line('            val catOk = category == "ALL" || item.category == category'
               if has_chips else '            val catOk = true')
        e.line("            val qOk = q.isEmpty() || item.name.lowercase().contains(q)"
               if has_search else "            val qOk = true")
        e.line("            catOk && qOk")
        e.line("        }")
        e.line("        gridAdapter.submit(filtered)")
    else:
        e.line("        val filtered = allWalls.filter { wall ->")
        e.line('            series == "ALL" || wall.series == series'
               if has_chips else "            true")
        e.line("        }")
        e.line("        gridAdapter.submit(filtered)")
    if count_id:
        e.line(f"        updateCount(findViewById(R.id.{count_id}), "
               "filtered.size)" if False else
               f"        updateCount(findViewById(R.id.{count_id}))")
        # NOTE: updateCount reads the adapter; filtered count shown when asked.
    if empty_blocks:
        eb = empty_blocks[0]
        e.line(f"        val empty = filtered.isEmpty()")
        e.line(f"        findViewById<View>(R.id.{eb['id']}).visibility =")
        e.line("            if (empty) View.VISIBLE else View.GONE")
        e.line(f"        findViewById<View>(R.id.{grid['id']}).visibility =")
        e.line("            if (empty) View.GONE else View.VISIBLE")
        e.line("        if (empty) {")
        e.line(f"            findViewById<View>(R.id.{eb['primary_id']}).focusFirst()")
        e.line("        }")
    e.line("    }")
    e.line()
    if count_id:
        e.line("    private fun updateCount(view: TextView) {")
        if source == "icons":
            e.line("        val shown = gridAdapter.itemCount")
            e.line('        view.text = if (shown == allIcons.size) "${allIcons.size} icons"')
            e.line('        else "$shown / ${allIcons.size} icons"')
        else:
            e.line("        val shown = gridAdapter.itemCount")
            e.line('        view.text = if (shown == allWalls.size) "${allWalls.size} wallpapers"')
            e.line('        else "$shown / ${allWalls.size} wallpapers"')
        e.line("    }")
        e.line()


def _activity_bar_toggle(e: Emitter, block: dict, links: dict) -> None:
    name = IDDENorm(block["id"])
    first = block["button_id"] if block["type"] == "updatebar" else block["buttons"][0]["id"]
    up = (links.get(first) or {}).get("up")
    down = (links.get(first) or {}).get("down")
    e.line(f"    private fun set{name}Visible(visible: Boolean) {{")
    e.line(f"        val bar = findViewById<View>(R.id.{block['id']})")
    e.line("        if (visible) {")
    e.line("            TvFocus.reveal(bar)")
    chain = [f"R.id.{up}"] if up else []
    chain.append(f"R.id.{first}")
    if down:
        chain.append(f"R.id.{down}")
    if len(chain) >= 2:
        views = ", ".join(f"findViewById<View>({c})" for c in chain)
        e.line(f"            DpadNav.chainVertical({views})")
    e.line(f"            findViewById<View>(R.id.{first}).focusFirst()")
    e.line("        } else {")
    e.line("            bar.visibility = View.GONE")
    if up and down:
        e.line(f"            DpadNav.chainVertical(findViewById(R.id.{up}), "
               f"findViewById(R.id.{down}))")
    e.line("        }")
    e.line("    }")
    e.line()


def IDDENorm(block_id: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in block_id.split("_"))


def _apply_anim_overrides(code: str, anim: dict) -> str:
    """Bake non-default anim settings into TvFocus calls.

    Defaults stay bare (`TvFocus.attach(view)`) so generated code reads
    clean; only overridden values are spelled out as named arguments.
    """
    import re
    scale = anim.get("focusScale", 1.06)
    if scale != 1.06:
        code = re.sub(
            r"TvFocus\.attach\((findViewById\(R\.id\.[a-z0-9_]+\)(?:\.[a-z_]+\([^)]*\))*)\)",
            r"TvFocus.attach(\1, scale = %sf)" % scale, code)
    item = anim.get("itemScale", 1.04)
    if item != 1.04:
        code = re.sub(
            r"TvFocus\.zoomItems\((findViewById\(R\.id\.[a-z0-9_]+\))\)",
            r"TvFocus.zoomItems(\1, %sf)" % item, code)
    stagger = anim.get("staggerMs", 28)
    enter_ms = anim.get("enterMs", 220)
    if stagger != 28 or enter_ms != 220:
        code = re.sub(
            r"TvFocus\.playEnter\((findViewById\(R\.id\.[a-z0-9_]+\))\)",
            r"TvFocus.playEnter(\1, staggerMs = %dL, durationMs = %dL)"
            % (stagger, enter_ms), code)
    return code


# --------------------------------------------------------------------------
# Strings + manifest
# --------------------------------------------------------------------------

def render_strings(spec: Spec) -> str:
    strings = dict(spec.extra_strings)
    strings.update(spec.extracted)
    e = Emitter()
    e.line('<?xml version="1.0" encoding="utf-8"?>')
    e.line(f"<!-- Generated by tools/build_ui.py for {spec.activity}. -->")
    e.line("<!-- --apply merges these into values/strings.xml (skipping names")
    e.line("     that already exist); Pop inherits them via the string mirror. -->")
    e.line("<resources>")
    for name in sorted(strings):
        e.line(f"    <string name=\"{name}\">{esc(strings[name])}</string>")
    e.line("</resources>")
    e.line()
    return e.text()


def manifest_entry(spec: Spec) -> str:
    header = _blocks_of(spec, "header")[0]
    label = header["title"]
    label_ref = label if label.startswith("@") else "@string/app_name"
    return (
        "        <activity\n"
        f'            android:name=".{spec.activity}"\n'
        '            android:exported="false"\n'
        f'            android:label="{label_ref}"\n'
        '            android:theme="@style/Theme.CoreBuilds" />\n'
    )

