#!/usr/bin/env python3
"""Generate the Core Builds Banners companion's resources from the glyph pack.

The companion (``banners/``, package ``tv.corebuilds.iconpack.banners``) is
the classic pack's 16:9 twin: same components, same fallback furniture, but
every appfilter entry points at ``<drawable>_banner`` instead of
``<drawable>``. Launchers read an appfilter out of the pack's own APK, so this
second package is what lets the in-app Glyphs/Banners toggle change what a
launcher auto-applies.

Derived from the glyph pack's *generated* files, not from the catalog, on
purpose: the two packages then cannot disagree about which components are
covered, and there is no second copy of build_icons.py's component-expansion
rules to drift. Run it after ``tools/build_icons.py`` and
``tools/build_banners.py`` (the banner PNGs it checks for).

The PNGs are not written here. banners/build.gradle.kts copies them from
app/src/main/res/drawable-nodpi at build time, so each banner exists once in
git.

    python tools/build_banners_pack.py           # write
    python tools/build_banners_pack.py --check   # fail on drift (CI)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP_MAIN = ROOT / "app" / "src" / "main"
PACK_MAIN = ROOT / "banners" / "src" / "main"

SRC_APPFILTER = APP_MAIN / "res" / "xml" / "appfilter.xml"
SRC_DRAWABLE = APP_MAIN / "res" / "xml" / "drawable.xml"
SRC_PNG = APP_MAIN / "res" / "drawable-nodpi"

HEADER = ("<!-- Generated by tools/build_banners_pack.py from the glyph pack's "
          "appfilter. Do not edit by hand. -->")
ITEM = re.compile(r'^(\s*<item component="[^"]+" drawable=")([^"]+)("/>)$')
DRAWABLE_ITEM = re.compile(r'^\s*<item drawable="([^"]+)" />$')
CATEGORY = re.compile(r'^\s*<category title="([^"]+)" />$')

STRINGS = """<?xml version="1.0" encoding="utf-8"?>
{header}
<resources>
    <string name="app_name">Core Builds Banners</string>
</resources>
"""


def fail(message: str) -> None:
    print(f"::error::{message}")
    raise SystemExit(1)


def appfilter() -> str:
    """The glyph appfilter with every item re-pointed at its banner."""
    out: list[str] = []
    items = 0
    for line in SRC_APPFILTER.read_text(encoding="utf-8").splitlines():
        if line.startswith("<!-- Generated by"):
            out.append(HEADER)
            continue
        m = ITEM.match(line)
        if m:
            drawable = m.group(2)
            if drawable.endswith("_banner"):
                fail(f"glyph appfilter already maps to a banner ({drawable}); "
                     "the companion would double the suffix")
            out.append(f"{m.group(1)}{drawable}_banner{m.group(3)}")
            items += 1
        else:
            out.append(line)
    if items == 0:
        fail(f"no <item> entries parsed from {SRC_APPFILTER.relative_to(ROOT)}")
    return "\n".join(out) + "\n"


def drawable_xml() -> str:
    """The launcher icon browser: every glyph pack section, as banners.

    The glyph pack lists glyphs only and this package lists banners only, so
    each pack's browser offers its own art style. Same sections, same order,
    "Square · X" retitled "Banners · X", each item re-pointed at its banner.
    """
    out = ['<?xml version="1.0" encoding="utf-8"?>', HEADER, "<resources>"]
    for line in SRC_DRAWABLE.read_text(encoding="utf-8").splitlines():
        cat = CATEGORY.match(line)
        if cat:
            title = cat.group(1)
            if not title.startswith("Square \u00b7 "):
                fail(f"unexpected drawable.xml section {title!r}; the glyph pack "
                     "lists its square glyphs only")
            out.append(line.replace(title, "Banners \u00b7 " + title[len("Square \u00b7 "):]))
            continue
        item = DRAWABLE_ITEM.match(line)
        if item:
            if item.group(1).endswith("_banner"):
                fail(f"the glyph pack's drawable.xml lists a banner ({item.group(1)}); "
                     "banners belong to the companion only")
            out.append(line.replace(f'"{item.group(1)}"', f'"{item.group(1)}_banner"'))
    out.append("</resources>")
    if len(out) <= 4:
        fail("no sections found in the glyph pack's drawable.xml")
    return "\n".join(out) + "\n"


def outputs() -> dict[Path, str]:
    af = appfilter()
    return {
        PACK_MAIN / "res" / "xml" / "appfilter.xml": af,
        # Same res/xml + assets pair as the glyph pack: several older
        # launchers read only the assets copy.
        PACK_MAIN / "assets" / "appfilter.xml": af,
        PACK_MAIN / "res" / "xml" / "drawable.xml": drawable_xml(),
        PACK_MAIN / "res" / "values" / "strings.xml": STRINGS.format(header=HEADER),
    }


def check_art(files: dict[Path, str]) -> None:
    """Every drawable the companion names must exist in the art it copies."""
    names = set()
    for text in (files[PACK_MAIN / "res" / "xml" / "appfilter.xml"],
                 files[PACK_MAIN / "res" / "xml" / "drawable.xml"]):
        names |= set(re.findall(r'drawable="([^"]+)"', text))
        names |= set(re.findall(r'img\d+="([^"]+)"', text))
    missing = sorted(n for n in names if not (SRC_PNG / f"{n}.png").is_file())
    if missing:
        fail(f"{len(missing)} drawable(s) the companion names are not in "
             f"app/src/main/res/drawable-nodpi: {', '.join(missing[:5])}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed files differ")
    args = parser.parse_args(argv)

    files = outputs()
    check_art(files)
    if args.check:
        stale = [p for p, text in files.items()
                 if not p.is_file() or p.read_text(encoding="utf-8") != text]
        if stale:
            fail("banners companion is stale against the glyph pack: "
                 + ", ".join(str(p.relative_to(ROOT)) for p in stale)
                 + "; run python tools/build_banners_pack.py")
        items = files[PACK_MAIN / "res" / "xml" / "appfilter.xml"].count("<item ")
        print(f"banners companion in sync - {items} appfilter entries, "
              "every drawable present")
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    items = files[PACK_MAIN / "res" / "xml" / "appfilter.xml"].count("<item ")
    print(f"banners companion written - {items} appfilter entries -> banner art")
    return 0


if __name__ == "__main__":
    sys.exit(main())
