#!/usr/bin/env python3
"""Write the icon pack's banner XML (the default style) from the glyph pack's.

Since 1.9.5 banners are the default again: the icon pack
(``tv.corebuilds.iconpack``) maps every component to ``<drawable>_banner``,
so a launcher that applies Core Builds gets 16:9 art. Square glyphs live in
Core Builds Glyphs (``glyphs/``, package ``tv.corebuilds.iconpack.glyphs``),
whose appfilter maps the same components to ``<drawable>``. Launchers read an
appfilter out of the pack's own APK, so that second package is what lets the
in-app Banners/Glyphs toggle change what a launcher auto-applies.

Derived from the glyph pack's *generated* files (``tools/build_icons.py``
writes them into ``glyphs/``), not from the catalog, on purpose: the two
packages then cannot disagree about which components are covered, and there
is no second copy of build_icons.py's component-expansion rules to drift.
Run it after ``tools/build_icons.py`` and ``tools/build_banners.py`` (the
banner art it checks for).

No art is written here. The banners are the icon pack's own; the glyph
companion's glyphs are copied from app/src/main/res/drawable-nodpi by
glyphs/build.gradle.kts at build time, so each file exists once in git.

    python tools/build_banners_pack.py           # write
    python tools/build_banners_pack.py --check   # fail on drift (CI)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from drawable_art import art_path, read_aliases  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
APP_MAIN = ROOT / "app" / "src" / "main"
GLYPH_MAIN = ROOT / "glyphs" / "src" / "main"

SRC_APPFILTER = GLYPH_MAIN / "res" / "xml" / "appfilter.xml"
SRC_DRAWABLE = GLYPH_MAIN / "res" / "xml" / "drawable.xml"
SRC_PNG = APP_MAIN / "res" / "drawable-nodpi"

HEADER = ("<!-- Generated by tools/build_banners_pack.py from Core Builds "
          "Glyphs' appfilter. Do not edit by hand. -->")
ITEM = re.compile(r'^(\s*<item component="[^"]+" drawable=")([^"]+)("/>)$')
DRAWABLE_ITEM = re.compile(r'^\s*<item drawable="([^"]+)" />$')
CATEGORY = re.compile(r'^\s*<category title="([^"]+)" />$')

STRINGS = """<?xml version="1.0" encoding="utf-8"?>
{header}
<resources>
    <string name="app_name">Core Builds Glyphs</string>
</resources>
"""


def fail(message: str) -> None:
    print(f"::error::{message}")
    raise SystemExit(1)


def appfilter() -> str:
    """The glyph appfilter with every item re-pointed at its banner."""
    out: list[str] = []
    items = 0
    for line in SRC_APPFILTER.read_text(encoding="utf-8").splitlines():
        if line.startswith("<!-- Generated by"):
            out.append(HEADER)
            continue
        m = ITEM.match(line)
        if m:
            drawable = m.group(2)
            if drawable.endswith("_banner"):
                fail(f"glyph appfilter already maps to a banner ({drawable}); "
                     "the banner appfilter would double the suffix")
            out.append(f"{m.group(1)}{drawable}_banner{m.group(3)}")
            items += 1
        else:
            out.append(line)
    if items == 0:
        fail(f"no <item> entries parsed from {SRC_APPFILTER.relative_to(ROOT)}")
    return "\n".join(out) + "\n"


def drawable_xml() -> str:
    """The launcher icon browser: every glyph pack section, as banners.

    Core Builds Glyphs lists glyphs only and the icon pack lists banners
    only, so each pack's browser offers its own art style. Same sections, same order,
    "Square · X" retitled "Banners · X", each item re-pointed at its banner.
    """
    out = ['<?xml version="1.0" encoding="utf-8"?>', HEADER, "<resources>"]
    for line in SRC_DRAWABLE.read_text(encoding="utf-8").splitlines():
        cat = CATEGORY.match(line)
        if cat:
            title = cat.group(1)
            if not title.startswith("Square \u00b7 "):
                fail(f"unexpected drawable.xml section {title!r}; the glyph pack "
                     "lists its square glyphs only")
            out.append(line.replace(title, "Banners \u00b7 " + title[len("Square \u00b7 "):]))
            continue
        item = DRAWABLE_ITEM.match(line)
        if item:
            if item.group(1).endswith("_banner"):
                fail(f"the glyph pack's drawable.xml lists a banner ({item.group(1)}); "
                     "banners belong to the icon pack only")
            out.append(line.replace(f'"{item.group(1)}"', f'"{item.group(1)}_banner"'))
    out.append("</resources>")
    if len(out) <= 4:
        fail("no sections found in the glyph pack's drawable.xml")
    return "\n".join(out) + "\n"


def outputs() -> dict[Path, str]:
    af = appfilter()
    dx = drawable_xml()
    return {
        APP_MAIN / "res" / "xml" / "appfilter.xml": af,
        # The res/xml + assets pair: several older launchers read only the
        # assets copy.
        APP_MAIN / "assets" / "appfilter.xml": af,
        APP_MAIN / "res" / "xml" / "drawable.xml": dx,
        APP_MAIN / "assets" / "drawable.xml": dx,
        # The companion's own label, as launchers list it.
        GLYPH_MAIN / "res" / "values" / "strings.xml": STRINGS.format(header=HEADER),
    }


def check_art(files: dict[Path, str]) -> None:
    """Every banner the icon pack names must exist in its own art."""
    aliases = read_aliases(APP_MAIN / "res" / "values")
    names = set()
    for text in (files[APP_MAIN / "res" / "xml" / "appfilter.xml"],
                 files[APP_MAIN / "res" / "xml" / "drawable.xml"]):
        names |= set(re.findall(r'drawable="([^"]+)"', text))
        names |= set(re.findall(r'img\d+="([^"]+)"', text))
    missing = sorted(n for n in names
                     if not art_path(SRC_PNG, n, aliases).is_file())
    if missing:
        fail(f"{len(missing)} drawable(s) the icon pack names are not in "
             f"app/src/main/res/drawable-nodpi: {', '.join(missing[:5])}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed files differ")
    args = parser.parse_args(argv)

    files = outputs()
    check_art(files)
    if args.check:
        stale = [p for p, text in files.items()
                 if not p.is_file() or p.read_text(encoding="utf-8") != text]
        if stale:
            fail("the icon pack's banner XML is stale against the glyph pack: "
                 + ", ".join(str(p.relative_to(ROOT)) for p in stale)
                 + "; run python tools/build_banners_pack.py")
        items = files[APP_MAIN / "res" / "xml" / "appfilter.xml"].count("<item ")
        print(f"banner appfilter in sync - {items} entries, "
              "every drawable present")
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    items = files[APP_MAIN / "res" / "xml" / "appfilter.xml"].count("<item ")
    print(f"banner appfilter written - {items} entries -> banner art "
          "(icon pack); glyphs stay in Core Builds Glyphs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
