#!/usr/bin/env python3
"""Emit values-sw720dp/dimens.xml for every module: the same metrics, doubled.

Why this file exists
--------------------
Android TV panels do not agree on the dp box they report. A 1080p panel reports
960x540dp; a 4K panel commonly reports twice that (1920x1080dp) because its
density bucket doubles while the physical panel stays the size of a wall. A
layout written in dp then renders at half the physical size on the 4K set - a
16sp label becomes the 1080p set's 8sp equivalent at the same 3m viewing
distance, which is unreadable, and the 48dp focus floor stops being a floor in
any physical sense.

The fix is the platform's own: a smallest-width qualifier. sw720dp matches
exactly the panels whose dp box is the doubled one (smallest width 1080dp), and
never the 960x540dp sets. Doubling every metric in the qualified file makes the
two panels render the same *picture*: same column counts (the grid divides pane
width by tile pitch, both doubled), same physical type sizes, same focus rings.

Hand-maintaining a doubled copy of ~45 dimens in three modules is a drift farm,
so this generator owns the qualified file. It is a straight x2 of values/
dimens.xml; anything that must NOT scale (there is nothing today) would need a
skip-list entry here, loudly.

Wiring: run it after editing any values/dimens.xml. tools/prepare_release.py
lists it in BUILDERS and tests/test_tv_layout_fit.py asserts the qualified file
is exactly double the base one, in every module, so a hand-edited or stale copy
fails CI.
"""
from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES = {
    "app": ROOT / "app/src/main/res",
    "pop": ROOT / "pop/src/main/res",
    "pixel-neon": ROOT / "pixel-neon/app/src/main/res",
}
HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tools/build_scale_variants.py - do not edit by hand.

     values-sw720dp matches 4K panels that report the doubled dp box
     (1920x1080dp instead of 960x540dp). Every metric is exactly twice the base
     values/dimens.xml so both panels render the same physical picture: same
     type sizes at 3m, same focus floors, same grid column counts (the span
     arithmetic divides pane width by tile pitch, and both double).
     Edit values/dimens.xml and re-run the generator. -->
"""


def double(text: str) -> str:
    def bump(m: re.Match) -> str:
        value = float(m.group(1))
        scaled = value * 2
        return f">{scaled:g}{m.group(2)}</dimen>"
    return re.sub(r">(-?\d+(?:\.\d+)?)(dp|sp|dip)</dimen>", bump, text)


def main() -> int:
    for module, res in MODULES.items():
        base = res / "values" / "dimens.xml"
        out = res / "values-sw720dp" / "dimens.xml"
        text = base.read_text(encoding="utf-8")
        body = text[text.index("<resources>"):]
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(HEADER + double(body), encoding="utf-8")
        # sanity: same names, doubled numbers
        b = {d.get("name"): (d.text or "") for d in ET.parse(base).getroot() if d.tag == "dimen"}
        s = {d.get("name"): (d.text or "") for d in ET.parse(out).getroot() if d.tag == "dimen"}
        assert set(b) == set(s), f"{module}: name sets differ"
        for name, bv in b.items():
            m = re.fullmatch(r"(-?\d+(?:\.\d+)?)(dp|sp|dip)", bv.strip())
            if not m:
                continue
            expect = f"{float(m.group(1)) * 2:g}{m.group(2)}"
            assert s[name].strip() == expect, f"{module}: {name} {s[name]} != {expect}"
        print(f"✓ {module}: values-sw720dp/dimens.xml ({len(s)} dimens, x2)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
