"""Shared art-format knowledge for the icon-pack pipeline.

Glyphs, banners, and fallback furniture ship as **lossless WebP**: ~62%
smaller than the PNGs they replaced, pixel-identical (see
docs/research/iconpack-size-and-gaps-2026-09.md). Resource lookup is
extension-agnostic, so no Kotlin, appfilter, or drawable.xml entry changes
— only the file bytes on disk.

Branding (`cb_banner`, all mipmaps) deliberately stays PNG: the TV banner
and launcher icon are brand assets outside the measured set, and Google's
own guidance excludes launcher icons from WebP.

Byte-identical renders ship once: within each art family the
lexicographically-first drawable keeps the bitmap and later names become
`<drawable>` aliases, so every appfilter name still resolves.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

ART_EXT = ".webp"
# drawable-nodpi PNGs that are branding, not pack art, and must survive the
# format migration's stale-file cleanup.
BRANDING_PNGS = frozenset({"cb_banner.png"})

_ALIAS_RE = re.compile(r'<drawable name="([^"]+)">@drawable/([^"<]+)</drawable>')


def read_aliases(values_dir: Path) -> dict[str, str]:
    """Alias name -> canonical name across the generated alias files."""
    found: dict[str, str] = {}
    for leaf in ("aliases.xml", "banner_aliases.xml"):
        path = values_dir / leaf
        if not path.is_file():
            continue
        for name, canon in _ALIAS_RE.findall(path.read_text(encoding="utf-8")):
            found[name] = canon
    return found


def art_path(nodpi_dir: Path, drawable: str,
             aliases: dict[str, str] | None = None) -> Path:
    """On-disk art file for a drawable name, following aliases.

    Branding names resolve to their PNG; everything else to WebP.
    """
    if aliases and drawable in aliases:
        drawable = aliases[drawable]
    if f"{drawable}.png" in BRANDING_PNGS:
        return nodpi_dir / f"{drawable}.png"
    return nodpi_dir / f"{drawable}{ART_EXT}"


def write_aliases_file(path: Path, mapping: dict[str, str], generated_by: str) -> None:
    """Write a values alias file; mapping is alias -> canonical."""
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             f'<!-- Generated by {generated_by}. Do not edit by hand. -->',
             '<resources>']
    for alias in sorted(mapping):
        lines.append(f'    <drawable name="{alias}">@drawable/{mapping[alias]}</drawable>')
    lines.append('</resources>')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def alias_identical(files: list[Path]) -> dict[str, str]:
    """Map duplicate art files to their canonical twin, deleting the dupes.

    `files` are same-family art files (stems are drawable names). The
    lexicographically-first stem keeps the bitmap; every other identical
    file is deleted and returned as alias -> canonical. Deterministic: same
    bytes in, same aliases out.
    """
    by_hash: dict[str, list[Path]] = {}
    for path in files:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        by_hash.setdefault(digest, []).append(path)
    mapping: dict[str, str] = {}
    for group in by_hash.values():
        if len(group) < 2:
            continue
        ordered = sorted(group, key=lambda p: p.stem)
        canon = ordered[0].stem
        for dup in ordered[1:]:
            mapping[dup.stem] = canon
            dup.unlink()
    return mapping
