#!/usr/bin/env python3
"""
Core Builds Icon Pack — glyph ink boxes.

The Classic optical fit (tools/fit_classic_glyphs.py) and the banner lockup
(tools/build_banners.py) both need to know where each glyph's ink actually
sits on the 512 grid. A bounding box needs a rasteriser, and rasterisers
disagree by a pixel across versions, so the renderers must not measure at
render time or their output stops being a pure function of committed files.
Measurement happens here, once, and tools/glyph_metrics.json is committed.

This table used to be tools/pop_glyph_metrics.json, measured by Pop's tooling;
Pop is retired (2026-09-24) and the Classic pack owns it now.

    python tools/measure_glyphs.py           # re-measure (~30 s)
    python tools/measure_glyphs.py --check   # geometry unchanged since the last
                                             # measure? string work, no rasteriser

Re-run whenever tools/glyphs.py changes a glyph's shape, then rerun
tools/fit_classic_glyphs.py and the generators.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from glyphs import GLYPHS, GRID  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tools" / "glyph_metrics.json"

SAMPLE = 1024        # measure at 2x: a 1px rasteriser disagreement is half a unit
HAIRLINE = 1.0
_SENTINEL = "#000000"
_SW_RE = re.compile(r'stroke-width="([\d.]+)"')


def hairline_body(glyph: str) -> str:
    """The glyph's geometry with every stroke collapsed to a hairline.

    Strokes are collapsed because renderers add their own weight back;
    measuring them here would bake one weight into the table.
    """
    return _SW_RE.sub(f'stroke-width="{HAIRLINE}"', GLYPHS[glyph](_SENTINEL))


def geometry_bbox(glyph: str) -> list[float] | None:
    from PIL import Image
    from svg_renderer import svg2png

    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {GRID} {GRID}" '
           f'width="{SAMPLE}" height="{SAMPLE}">{hairline_body(glyph)}</svg>')
    png = svg2png(bytestring=svg.encode("utf-8"), output_width=SAMPLE,
                  output_height=SAMPLE, background_color=None)
    box = Image.open(io.BytesIO(png)).convert("RGBA").getchannel("A").getbbox()
    if not box:
        return None
    k = GRID / SAMPLE
    return [round(v * k, 2) for v in box]


def geometry_fingerprint() -> str:
    """Digest of the exact geometry the table was measured from, so a glyph
    edit without a re-measure fails --check instead of silently mis-fitting."""
    h = hashlib.sha256()
    for name in sorted(GLYPHS):
        h.update(name.encode("utf-8"))
        h.update(hairline_body(name).encode("utf-8"))
    return h.hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if glyph geometry changed since the last measure")
    args = parser.parse_args(argv)

    if args.check:
        stored = json.loads(OUT.read_text(encoding="utf-8"))
        if stored.get("geometry_sha256") != geometry_fingerprint():
            print("::error::tools/glyph_metrics.json was measured from different "
                  "glyph geometry; run python tools/measure_glyphs.py, then "
                  "python tools/fit_classic_glyphs.py")
            return 1
        print(f"glyph metrics match the geometry - {stored['count']} glyphs")
        return 0

    metrics: dict[str, list[float]] = {}
    empty: list[str] = []
    for name in sorted(GLYPHS):
        box = geometry_bbox(name)
        if box is None:
            empty.append(name)
        else:
            metrics[name] = box
    payload = {
        "note": ("Ink boxes of tools/glyphs.py geometry on the 512 grid, strokes "
                 "collapsed to a hairline. Generated by tools/measure_glyphs.py "
                 "- do not hand-edit."),
        "grid": GRID,
        "count": len(metrics),
        "geometry_sha256": geometry_fingerprint(),
        "metrics": metrics,
    }
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"measured {len(metrics)} glyphs -> {OUT.relative_to(ROOT)}")
    if empty:
        print(f"warning: {len(empty)} glyph(s) rendered empty: {', '.join(empty)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
