#!/usr/bin/env python3
"""
Core Builds Pop — glyph metrics.

Every icon in Pop is optically normalised: the mark inside the field is scaled
so its ink box is the same size on all 924 icons, and its stroke weight is
pre-divided by that scale so the linework still lands on one canonical weight
afterwards. Doing both is what stops "uniform" from meaning "all the same
container with wildly different marks rattling around inside it".

Scale needs a bounding box, and a bounding box needs a rasteriser. Rasterisers
disagree by a pixel or two across versions, and `popart.py` must be a pure
function of committed inputs or CI's SVG drift gate fails on a library bump
rather than on real drift. So measurement happens here, once, and the result
is committed to tools/pop_glyph_metrics.json. The renderer only ever reads it.

    python tools/measure_pop_glyphs.py

Re-run only when glyphs.py changes shape geometry.
"""
from __future__ import annotations

import io
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from popart import GRID, pop_body, strip_weights  # noqa: E402
from glyphs import GLYPHS  # noqa: E402
from svg_renderer import svg2png  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tools" / "pop_glyph_metrics.json"

# Measure at 2x so a 1px rasteriser disagreement is half a grid unit, well
# under the rounding we apply below.
SAMPLE = 1024
HAIRLINE = 1.0


def geometry_bbox(glyph: str) -> tuple[float, float, float, float] | None:
    """Ink box of the glyph's raw geometry, strokes reduced to a hairline.

    Strokes are collapsed first because the renderer adds them back at a
    computed width; measuring them here would bake one weight into the table
    and make the scale solve circular.
    """
    from PIL import Image

    body = strip_weights(pop_body(glyph), HAIRLINE)
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {GRID} {GRID}" '
           f'width="{SAMPLE}" height="{SAMPLE}">{body}</svg>')
    png = svg2png(bytestring=svg.encode("utf-8"),
                  output_width=SAMPLE, output_height=SAMPLE,
                  background_color=None)
    im = Image.open(io.BytesIO(png)).convert("RGBA")
    box = im.getchannel("A").getbbox()
    if not box:
        return None
    k = GRID / SAMPLE
    return tuple(round(v * k, 2) for v in box)


def main() -> int:
    metrics: dict[str, list[float]] = {}
    missing: list[str] = []
    for name in sorted(GLYPHS):
        box = geometry_bbox(name)
        if box is None:
            missing.append(name)
            continue
        metrics[name] = list(box)

    payload = {
        "note": ("Ink boxes of tools/glyphs.py geometry on the 512 grid, "
                 "strokes collapsed to a hairline. Generated by "
                 "tools/measure_pop_glyphs.py — do not hand-edit."),
        "grid": GRID,
        "count": len(metrics),
        "metrics": metrics,
    }
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n",
                   encoding="utf-8")
    print(f"\u2713 measured {len(metrics)} glyphs \u2192 {OUT.relative_to(ROOT)}")
    if missing:
        print(f"\u26a0 {len(missing)} glyph(s) rendered empty: "
              f"{', '.join(missing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
