#!/usr/bin/env python3
"""
Prepare an Icon Pack release: stamp every version surface, rebuild the
text-asset previews, and run the full gate suite — in one command, in the
order CI expects.

The eight version surfaces that must agree (check_suite_truth.py and
validate.py §5j cross-assert most of them, but only after you have run
this):

  1. app/build.gradle.kts            versionName — source of truth
  2. app/build.gradle.kts            versionCode (incremented by one)
  3. tools/catalog.json              meta.version
  4. app/src/main/assets/version.json  versionName, versionCode, counts,
                                     date, highlights (the build's own
                                     manifest; What's New reads it)
  5. suite.json                      iconpack versionName, versionCode, counts
  6. README.md                       suite-stamp block (build_readme_badge)
  7. AGENTS.md                       suite-table iconpack row (held to
                                     suite.json by check_agents_guide)
  8. CHANGELOG.md                    [Unreleased] -> [version] dated, fresh
                                     [Unreleased] on top (Keep a Changelog)

docs/IconPackList.md and the preview assets carry the version too, but they
are regenerated by the builders below, not stamped by hand.

Then the five text-asset builders (a version-stamp change without them
fails CI's drift gate on docs/preview.svg) and the gates. When this exits
0, the remaining steps are manual and deliberate:

  git add -A && git commit && push && PR to main -> squash-merge ->
  tag vX.Y.Z **on the merged main commit** -> push the tag.

  CI's build.yml refuses tags not ancestral to main, then builds and signs
  the APK, publishes the GitHub release, moves the floating `iconpack` tag,
  and only then copies the manifest to Latestrelease/version.json - the file
  installed copies poll. Nothing here touches that file: merging the bump PR
  must not tell anyone an unreleased build is out. Run tools/generate_release_metadata.py iconpack --apk <built apk>
  afterwards if the release needs the apkSha256 field.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GRADLE = ROOT / "app/build.gradle.kts"
CATALOG = ROOT / "tools/catalog.json"
VERSION_JSON = ROOT / "app/src/main/assets/version.json"
SUITE = ROOT / "suite.json"
README = ROOT / "README.md"
CHANGELOG = ROOT / "CHANGELOG.md"

README_START = "<!-- suite-stamp:start -->"
README_END = "<!-- suite-stamp:end -->"

BUILDERS = [
    "tools/build_icons.py",
    "tools/build_banners.py",
    "tools/build_branding.py",
    "tools/build_brand_preview.py",
    "tools/build_icon_review.py",
]
GATES = [
    "tools/validate.py",
    # Added for 1.9.0: the release command should run every gate the repo has,
    # not the subset that existed when it was written. check_ui_resources reads
    # the app module, check_appfilter_integrity proves every drawable the
    # filters name exists, and the mockup check compares the frames committed in
    # docs/ against the layouts they depict - a release that restacks screens
    # without regenerating them ships documentation of a UI nobody has.
    "tools/check_ui_resources.py",
    "tools/check_appfilter_integrity.py",
    "tools/build_app_ui_mockups.py --check",
    "tools/check_gradle_envelope.py",
    "-m unittest discover -s tests",
    "tools/check_suite_truth.py",
    "tools/audit_contract.py",
    "tools/build_issue_prefills.py --check",
]


def fail(message: str) -> None:
    print(f"✗ {message}", file=sys.stderr)
    raise SystemExit(1)


def run(command: str) -> None:
    print(f"\n$ python {command}")
    subprocess.run([sys.executable] + command.split(), cwd=ROOT, check=True)


def changelog_highlights(text: str) -> list[str]:
    """Top-level [Unreleased] bullets as one-line highlights.

    House style puts the name of a change in a bold lead, so the lead is the
    highlight and the bullet body is CHANGELOG business. Order follows what a
    release is meant to lead with - Added, then Changed, then Fixed - and the
    cap is the eight UpdateChecker renders before the update bar stops being
    a bar.
    """
    match = re.search(r"## \[Unreleased\]\n(.*?)(?=\n## \[)", text, re.S)
    if not match:
        return []
    body = match.group(1)
    sections: list[tuple[str, int]] = []
    for name in ("Added", "Changed", "Fixed"):
        m = re.search(rf"### {name}\n(.*?)(?=\n### |\Z)", body, re.S)
        sections.append((name, m.start(1) if m else -1))
    out: list[str] = []
    for name, _ in sections:
        m = re.search(rf"### {name}\n(.*?)(?=\n### |\Z)", body, re.S)
        if not m:
            continue
        for lead in re.findall(r"(?m)^- +\*\*(.+?)\*\*", m.group(1), re.S):
            lead = " ".join(lead.split()).rstrip(".")
            # A gate, test or generator named by its path is a receipt, not a
            # headline: the what's-new bar is read by people deciding whether
            # to update, and `tools/build_app_ui_mockups.py` is not a reason.
            # The convention is the backticked path in the lead, so a bullet
            # opts out of the card by naming its own machinery.
            if lead.startswith(("`tests/", "`test_", "`tools/", "`.github/")):
                continue
            if lead:
                out.append(lead)
            if len(out) >= 8:
                return out
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="the release version, e.g. 1.8.19")
    parser.add_argument("--skip-builders", action="store_true",
                        help="stamp versions only; do not rebuild previews")
    parser.add_argument("--skip-gates", action="store_true",
                        help="stamp and build only; do not run the gate suite")
    args = parser.parse_args()
    if not re.fullmatch(r"\d+\.\d+\.\d+", args.version):
        fail(f"version must be MAJOR.MINOR.PATCH, got {args.version!r}")

    # 1. Gradle: the source of truth (idempotent: re-running for a version
    # already stamped keeps the versionCode instead of double-bumping)
    gradle = GRADLE.read_text(encoding="utf-8")
    m_code = re.search(r"versionCode\s*=\s*(\d+)", gradle)
    m_name = re.search(r'versionName\s*=\s*"([^"]+)"', gradle)
    if not m_code:
        fail("no versionCode in app/build.gradle.kts")
    already = m_name is not None and m_name.group(1) == args.version
    new_code = int(m_code.group(1)) + (0 if already else 1)
    if not already:
        gradle = gradle.replace(f"versionCode = {m_code.group(1)}",
                                f"versionCode = {new_code}", 1)
    gradle = re.sub(r'versionName\s*=\s*"[^"]+"',
                    f'versionName = "{args.version}"', gradle, count=1)
    GRADLE.write_text(gradle, encoding="utf-8")
    print(f"1-2. gradle: versionName {args.version}, versionCode {new_code}"
          + (" (already stamped — code kept)" if already else ""))

    # 3. catalog meta.version
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    data["meta"]["version"] = args.version
    CATALOG.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")
    icons = data["icons"]
    icon_count = len(icons)
    component_count = sum(len(i.get("components", [])) for i in icons)
    print(f"3. catalog meta.version {args.version} "
          f"({icon_count} icons, {component_count} components)")

    # 4. app/src/main/assets/version.json (the published copy follows at tag time)
    latest = json.loads(VERSION_JSON.read_text(encoding="utf-8"))
    latest.update({
        "versionCode": new_code,
        "versionName": args.version,
        "iconCount": icon_count,
        "componentCount": component_count,
        "releaseDate": datetime.now(timezone.utc).date().isoformat(),
    })
    # 4b. Release highlights for the in-app what's-new card: the top-level
    # bullets of [Unreleased], lead phrase each, capped at the six the
    # update bar renders. Captured here, before step 8 moves the section
    # down, so the manifest carries exactly the notes this release ships.
    highlights = changelog_highlights(CHANGELOG.read_text(encoding="utf-8"))
    # An empty [Unreleased] (a re-run for the same version) keeps the
    # highlights already stamped rather than blanking the card.
    if highlights:
        latest["highlights"] = highlights
    VERSION_JSON.write_text(json.dumps(latest, indent=2) + "\n",
                            encoding="utf-8")
    print(f"4. version.json stamped (apkSha256 stays to the built APK), "
          f"{len(latest['highlights'])} highlights")

    # 5. suite.json iconpack
    suite = json.loads(SUITE.read_text(encoding="utf-8"))
    icon = suite["apps"]["iconpack"]
    icon.update({"versionName": args.version, "versionCode": new_code,
                 "iconCount": icon_count, "componentCount": component_count})
    SUITE.write_text(json.dumps(suite, indent=2) + "\n", encoding="utf-8")
    print("5. suite.json iconpack stamped")

    # 6. README suite-stamp block
    sys.path.insert(0, str(ROOT / "tools"))
    from build_readme_badge import block  # noqa: E402
    readme = README.read_text(encoding="utf-8")
    start, end = readme.index(README_START), readme.index(README_END)
    readme = (readme[:start] + block(suite) + readme[end + len(README_END):])
    README.write_text(readme, encoding="utf-8")
    print("6. README suite-stamp block regenerated")

    # 7. AGENTS.md suite table: the iconpack row must say the new version
    # (check_suite_truth.check_agents_guide and audit_contract both hold it
    # to suite.json)
    agents = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    stamped, n = re.subn(
        r"(`tv\.corebuilds\.iconpack` \| )`[0-9][0-9.]*`",
        rf"\g<1>`{args.version}`", agents, count=1, flags=re.M)
    if n != 1:
        fail("AGENTS.md suite table: no `tv.corebuilds.iconpack` version row")
    (ROOT / "AGENTS.md").write_text(stamped, encoding="utf-8")
    print("7. AGENTS.md suite table stamped")

    # 8. CHANGELOG: [Unreleased] -> [version] dated, fresh [Unreleased] on
    # top (idempotent: a second run for the same version is a no-op here)
    changelog = CHANGELOG.read_text(encoding="utf-8")
    if f"\n## [{args.version}] " in changelog or \
            changelog.startswith(f"## [{args.version}] "):
        print(f"8. CHANGELOG: [{args.version}] already dated — kept")
    else:
        if "\n## [Unreleased]\n" not in changelog and \
                not changelog.startswith("## [Unreleased]\n"):
            fail("CHANGELOG.md has no [Unreleased] section — write the "
                 "release notes first (Keep a Changelog)")
        today = datetime.now(timezone.utc).date().isoformat()
        changelog = changelog.replace("## [Unreleased]",
                                      f"## [Unreleased]\n\n## [{args.version}] "
                                      f"— {today}", 1)
        CHANGELOG.write_text(changelog, encoding="utf-8")
        print(f"8. CHANGELOG: [{args.version}] dated {today}, fresh "
              "[Unreleased] on top")

    # 7. builders regenerate docs/IconPackList.md + preview assets
    if not args.skip_builders:
        for builder in BUILDERS:
            run(builder)
    else:
        print("7. builders skipped (--skip-builders)")
        print("   ⚠ CI's text-asset drift gate will fail until they run")

    if not args.skip_gates:
        for gate in GATES:
            run(gate)
    else:
        print("gates skipped (--skip-gates)")

    print(f"""
✓ {args.version} (versionCode {new_code}) is stamped and green.

Remaining steps (manual, deliberate):
  1. git add -A && git commit
  2. push the session branch, open a PR to main, squash-merge
  3. git tag v{args.version} <merged main commit SHA>   # on main, not the PR head
  4. git push origin v{args.version}
     CI builds and signs the APK, publishes the release, moves `iconpack`.
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
